Q2
Kounty2Rolen/FSService pull request #3
Opened 2019-05-13 11:57 UTC by Kounty2Rolen

2019-05-13 13:15 UTC, troepolik requested changes

2019-05-13 13:15 UTC, troepolik commented on q2/q2/Program.cs
> +            System.Collections.Generic.List<Animal> animals = new System.Collections.Generic.List<Animal>();
заюзать  var,  вынести полное имя в using

2019-05-13 13:15 UTC, troepolik commented on q2/q2/Program.cs
> +    class Animal
вынести в отдельный класс

2019-05-13 15:27 UTC, troepolik requested changes

2019-05-13 15:27 UTC, troepolik commented on q2/q2/Class1.cs
> +    class Animal
хорошим тоном оформления является - для каждого класса отдельный файл.
создай папку Models , там создай под каждый класс файлик.
привыкай оформлять код

2019-05-13 15:51 UTC, Kounty2Rolen commented on q2/q2/Class1.cs
> +    class Animal
Хорошо, понялприянл, класс разбил на отдельные файлы.

2019-05-14 11:31 UTC, troepolik approved these changes

2019-05-14 11:34 UTC, merged