q3
Kounty2Rolen/FSService pull request #4
Opened 2019-05-30 11:20 UTC by Kounty2Rolen

2019-06-04 08:51 UTC, troepolik requested changes

2019-06-04 08:51 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                    if (reader.HasRows)
лишняя проверка

2019-06-04 08:51 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +        public List<string> GetValue(List<Animal> animal) {
где комментарии? что за метод, для чего? почуму так называется?
что это за параметр и почему возвращаемое значение List<string> хотя должно быть  List<Animal> ?

2019-06-04 08:51 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                                    animal.Add(new Kesha(reader));
по условию задания должен быть конструктор по умолчанию + метод Serialize()

2019-06-04 08:51 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +        public void display()
Для чего нужен этот метод? накопипастили друг у друга бездумно...

2019-06-04 08:51 UTC, troepolik commented on q2/q2/Models/MycatClass.cs
> +            Name = reader.GetValue(1).ToString();
а если будет 100 разных классов, в каждом будешь писать сериализацию Name  и всех остальных общих полей? уроки 2й лабы не усвоены...

2019-06-04 08:51 UTC, troepolik commented on q2/q2/Program.cs
> +                DBinit db = new DBinit();
коннекшен кто закроет?

2019-06-04 10:50 UTC, Kounty2Rolen commented on q2/q2/DB_Work/DBinit.cs
> +        public void display()
Dispose - Это метод для постановки некой "галочки" на том что мы больше не будем использовать объект  sqlc 
display-для вывода содержимого бд

2019-06-04 10:51 UTC, Kounty2Rolen commented on q2/q2/Models/MycatClass.cs
> +            Name = reader.GetValue(1).ToString();
Понял, метод сериализации можно было вынести в класс родитель Animal, не додумался...

2019-06-04 11:12 UTC, Kounty2Rolen commented on q2/q2/DB_Work/DBinit.cs
> +                    if (reader.HasRows)
Убрал

2019-06-04 11:49 UTC, Kounty2Rolen commented on q2/q2/Program.cs
> +                DBinit db = new DBinit();
FIX:закрыл в конце Program

2019-06-04 13:05 UTC, troepolik requested changes

2019-06-04 13:05 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +        public void display()
я не про этот метод спрашивал. мой комментарий стоит под методом display, который непонятно для чего был сделан

2019-06-04 13:05 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
>              sqlc.Dispose();
вместо этого использовать конструкцию using

2019-06-04 13:05 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +        public void GetValue(List<Animal> animal)
еще раз: зачем передавать список как параметр, а не возвращать его из метода?

2019-06-04 13:05 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                                animal[animal.Count-1].Serialize(reader);
1) зачем это лишнее обращение по индексу?
2) зачем этот дабл код , если будет 100 разных типов, вы 100 раз напишете animal[animal.Count-1].Serialize(reader);  ?

2019-06-04 13:05 UTC, troepolik commented on q2/q2/Models/AnimalClass.cs
> +            if (reader["Name"].ToString() != null)
зачем вызывать ToString() для сравнения с null ?

2019-06-04 13:05 UTC, troepolik commented on q2/q2/Models/AnimalClass.cs
> +                if (reader["injail"].ToString() != "false")
индусский код. смысл этого сравнения мне все равно не ясен.

2019-06-04 13:05 UTC, troepolik commented on q2/q2/Models/AnimalClass.cs
> +        }
хорошо, а где специфичные для наследников поля сериализуются? нигде я так понимаю, это надо сделать

2019-06-04 13:05 UTC, troepolik commented on q2/q2/Program.cs
> +                Console.WriteLine(ex.Message + "\n\n" + ex.StackTrace);
лучше использовать ex.ToString

2019-06-04 13:05 UTC, troepolik commented on q2/q2/Program.cs
> +            catch (Exception ex)
я хочу дополнительно увидеть обработку SqlException

2019-06-05 09:16 UTC, Kounty2Rolen commented on q2/q2/Models/AnimalClass.cs
> +                if (reader["injail"].ToString() != "false")
Injail по умолчанию False и если в бд эта переменная так же False то менять ее нет смысла

2019-06-05 11:15 UTC, Kounty2Rolen commented on q2/q2/DB_Work/DBinit.cs
> +                                animal[animal.Count-1].Serialize(reader);
Окей, запухнул в Foreach перед закрытием USING

2019-06-05 13:43 UTC, troepolik commented on q2/q2/Models/AnimalClass.cs
> +                if (reader["injail"].ToString() != "false")
ну значит нужно переделать хранение данных на нормальные типы.
if (reader["injail"].ToString() != "false") - эта операция обойдется вам в разы дороже чем присвоение переменной , поэтому так никто не делает

2019-06-05 13:50 UTC, troepolik requested changes

2019-06-05 13:50 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +        public List<Animal> GetValue()
называть методы нужно так чтобы сразу было понятно что они делают . например GetAnimals или GetAllRecords

2019-06-05 13:50 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +            List<Animal> animal = new List<Animal>();
старайся приучить себя использовать новые фишки-  var

2019-06-05 13:50 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                                    animal.Add(new mycat(reader));
еще раз. я не хочу видеть в конструкторе ридер. я хочу конструктор по умолчанию (без параметров)
+ вызов метода serialize
 при этом написать код так чтобы не было даблкода

2019-06-05 13:50 UTC, troepolik commented on q2/q2/Models/AnimalClass.cs
>              if (Convert.ToInt32(reader["age"]) >= 0)
зачем все эти лишние проверки... вроде как это поля должны быть обязательно заполнены для всех... зачем это лишний раз проверять

2019-06-05 14:03 UTC, Kounty2Rolen commented on q2/q2/DB_Work/DBinit.cs
> +                                    animal.Add(new mycat(reader));
animal.ForEach(x => { x.Serialize(reader);}); Так нормально?

2019-06-06 11:49 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                                    animal.Add(new mycat(reader));
можно, но я бы не создавал лишних циклов. просто сделал бы вызов после  кейса создания обхекта.

2019-06-06 11:53 UTC, troepolik submitted a review, later dismissed

2019-06-06 11:53 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                        animal.FindLast(x => { x.Serialize(reader);return true; });
а зачем лишний раз что -то искать? код попахивает...

2019-06-06 13:05 UTC, Kounty2Rolen commented on q2/q2/DB_Work/DBinit.cs
> +                        animal.FindLast(x => { x.Serialize(reader);return true; });
Если использовать list() из linq-а то получится конструкция больше, я пробовал list тоже в лямбду засунуть но там была ошибка.
А так получилось бы 
Var x= animal.Last();
x serialize(reader);
А при лямбде 
animal.last(x=>{x.serialize(reader);});
Но он выбивает ошибку, уже не помню какую к вечеру запушу исправленный вариант

2019-06-08 16:43 UTC, troepolik requested changes

2019-06-08 16:43 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                        animal.Add(a);
ну наконец-то , то что я хотел от вас увидеть.
теперь код не дублируется.

2019-06-08 16:43 UTC, troepolik commented on q2/q2/Program.cs
> +            //}
так, вот тут я хочу чтобы обрабатывались оба типа ошибок. бывает требуется разные типы либо логировать по разному, либо какие-то пробрасывать дальше, а какие-то нет.
вобщем давайте так: если возникнет обычный эксепшен , то выводим какое-нить дополнительно сообщение в консоль.

2019-06-09 10:18 UTC, Kounty2Rolen commented on q2/q2/DB_Work/DBinit.cs
> +                        animal.Add(a);
вот, а то мы полезли в рефлексию вообще

2019-06-09 10:52 UTC, troepolik commented on q2/q2/DB_Work/DBinit.cs
> +                        animal.Add(a);
это тоже будет, позже.

2019-06-12 15:17 UTC, troepolik approved these changes

2019-06-12 15:18 UTC, merged